name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODI5MWJhMTEtMjU5NC00ZTk2LWJjNmItNmU3Y2Y3NTNmZTkyIiwidGVuYW50X2lkIjoiYTIyMGFmODQ5Y2ExZjQxYzViMWQ3ZDI0YjEyMGY0MTYyNWUwMDQzNGUzYTlhNGQzYjA1YzA0YmFkMTc3YmVkMiIsImludGVybmFsX3NlY3JldCI6IjBkYjM4ZmJiLTI1ZWItNDIzOS04MTBlLTA0ZDU0YTk1MmNiOCJ9.WHIl6kSCRqRxfdwD8_0UY4Db_-pry_SG983GphbQTXk"
JWT_SECRET = "kavya26"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
